apiVersion: configuration.konghq.com/v1
kind: TCPIngress
metadata:
  name: echo-tcp
  namespace: default
spec:
  rules:
  - port: 9000          # Kong listens on this port
    backend:
      serviceName: echo-server
      servicePort: 3000 # Your appâ€™s internal port