apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: namespace
  namespace: flux-system
resources:
  - echo-server-namespace.yaml
  - voice-bot-3-namespace.yaml
  - kong-namespace.yaml