apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-values
  namespace: echo-server
data:
  values.yaml: |
    replicaCount: 2
    image:
      tag: "latest"
    service:
      type: NodePort
    image:
      repository: nikhildhole/express-rest-demo