apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kong-helmrelease.yaml
  - kong-values.yaml
  - gateway.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/latest/download/standard-install.yaml