apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespace
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./clusters/dev/apps/echo-server
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
