apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./clusters/dev/apps/echo-server
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
      - name: namespace
      - name: infrastructure
    wait: true