apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./clusters/dev/infrastructure/kong
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespace
  wait: true